import Provider from "@/components/Providers";
import "./globals.css";
import { Inter , Poppins , Oswald , Roboto   } from "next/font/google";



const oswald = Oswald({ subsets: ['latin'] });
// const poppins = Poppins({ subsets: ['latin'] });

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  bg-white`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
