import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <div className="  grid lg:grid-cols-3 grid-cols-1 p-5   ">
          <div className="left__side hidden lg:block bg-blue-200 w-full h-95v rounded-xl  "></div>

          <div className="right__side lg:col-span-2  w-full bg-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
